#!/bin/bash

echo "Installing GitBook plugins"
gitbook install

echo "Building the book (this could take around 5 minutes)"
gitbook build

echo "Updating the deployment branch (deployed)"
git checkout deployed
rm -fr gitbook styles images resources activities week* index.html search_index.json *.jpg *.png
mv ./_book/* .
git add -A
git commit -m "build handbook"

echo "Deploying to Heroku"
git push --force heroku deployed:master

echo "Deployment complete!"
git checkout master

echo "Don't forget to push to origin ;)"
